services:
  trace-anything:
    container_name: trace-anything
    image: denden047/trace-anything
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/home/user/work/:rw
    command: /bin/bash
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    ports:
      - 8080:8080
      - 8020:8020
      - 7860:7860
    shm_size: "32gb"
    tty: true
    gpus: all
